name: running the terraform code and generating the inventory file 

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/kcluser25   # all steps use this folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
            cd /home/kcluser25
            terraform init
            terraform apply --auto-approve
            terraform output instance_public_ip  > ip.txt
            echo "" >> ip.txt 

      - name: Prepare Ansible inventory
        run: |
          cd /home/kcluser25
          echo "[centos9]" > inventory
          if [ -s ip.txt ]; then
            while IFS= read -r ip; do
              echo "$ip ansible_user=kcluser25 host_key_checking = False become_user=root become_method=sudo ansible_ssh_private_key_file=/home/kcluser25/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3 ansible_become=true" >> inventory
            done < ip.txt
          else
            echo "ip.txt is empty!"
          fi
  

      - name: Run Ansible Playbook
        run: |
          cd /home/kcluser25
          ansible-playbook -i inventory playbook1-adduser.yaml --become
          
   
